@startuml
actor  "Main"                    as Main
participant ":TopicManager"       as TM
participant ":UserManager"        as UM
participant ":KaaSAPI"            as KaaS
participant ":VaultAPI"           as VaultAPI
participant ":CollectorManager"   as CM

loop for each dir in sources/*

  Main -> Main++: parseKafkaConfig(dir/kafka.yml)
  deactivate Main

  Main  -> TM++: process(Topic)
  TM -> KaaS++: createTopic(Topic)
  TM <-- KaaS : OK
  deactivate KaaS
  Main <-- TM: Topic
  deactivate TM

  Main  -> UM++: process(User, Topic)
  
  UM -> KaaS++: createUser(User)
  UM <-- KaaS : OK
  deactivate KaaS

  UM ->> VaultAPI: saveUserCredentials(User)

  UM -> KaaS++: createPermission(Perm)
  UM <-- KaaS : OK
  deactivate KaaS


  Main <-- UM: User + Permission
  deactivate UM

  Main -> CM++: process(dir/main.yml)
  CM -> CM++: deployCollector()
  deactivate CM
  Main <-- CM: OK
  deactivate CM


end loop

hide footbox
@enduml
